name: Deploy

on:
 release:
  types: [published]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Create Release Directory
     run: mkdir -p _site/{{ release.name }}
   - name: Copy Site Content
     run: cp -r ./* _site/{{ release.name }}
   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./_site
      keep_files: true
