name: Deploy

on:
 release:
  types: [published]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Create version directory
     run: |
       VERSION-${{ github.ref_name }}
       VERSION_DIR-"./public/v${VERSION}"
       mkdir -p "$VERSION_DIR"

       files_to_copy=("en" "ru" "index.html")

       for file in "${files_to_copy[@]}"; do
          cp -r "./${file}" "$VERSION_DIR/"
       done
   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v4
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./VERSION_DIR
      keep_files: true
