name: Deploy

on:
 release:
  types: [published]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Create v1 directory
     run: mkdir -p _site/v1
   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v1
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./_site
      keep_files: true
